# Umbrella charts required (sub-) chart name
operator:
  operator:
    replicaCount: 1

  console:
    ingress:
      enabled: true
      ingressClassName: ""
      labels: { }
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      tls: [ ]
      host: minio-operator.dieren.gerull.nl
      path: /
      pathType: Prefix