operator:
  operator:
    replicaCount: 2

  console:
    ingress:
      enabled: false
      ingressClassName: ""
      labels: { }
      annotations: { }
      tls: [ ]
      host: minio-operator.dieren.gerull.nl
      path: /
      pathType: Prefix
